# emacs: -*- mode: python; py-indent-offset: 4; indent-tabs-mode: nil -*-
# vi: set ft=python sts=4 ts=4 sw=4 et:
"""Multimodal Surface Matching (MSM) interface."""

from pathlib import Path

from nipype.interfaces.base import (
    CommandLine,
    CommandLineInputSpec,
    File,
    TraitedSpec,
    traits,
)


class MSMInputSpec(CommandLineInputSpec):
    """Input specification for MSM (Multimodal Surface Matching) interface."""

    in_mesh = File(
        exists=True,
        mandatory=True,
        argstr='--inmesh=%s',
        desc='input mesh (VTK, ASCII, GIFTI). Must be a sphere.',
    )
    out_base = File(
        name_source=['in_mesh'],
        name_template='%s_msm',
        argstr='--out=%s',
        desc='output basename',
    )
    reference_mesh = File(
        exists=True,
        argstr='--refmesh=%s',
        desc='reference mesh (VTK, ASCII, GIFTI). Must be a sphere. '
        'If not included, algorithm assumes reference mesh is equivalent to input.',
    )
    in_data = File(
        exists=True,
        argstr='--indata=%s',
        desc='scalar or multivariate data for input (ASCII .asc/.dpv/.txt or GIFTI .func.gii/.shape.gii)',
    )
    reference_data = File(
        exists=True,
        argstr='--refdata=%s',
        desc='scalar or multivariate data for reference (ASCII .asc/.dpv/.txt or GIFTI .func.gii/.shape.gii)',
    )
    transformed_mesh = File(
        exists=True,
        argstr='--trans=%s',
        desc='Transformed source mesh (output of previous registration). Use to initialize current registration.',
    )
    in_register = File(
        exists=True,
        argstr='--in_register=%s',
        desc='Input mesh at data resolution. Used to resample data onto input mesh if supplied at '
        'different resolution. Must be in alignment with either input_mesh or (if supplied) '
        'transformed source mesh. Use with caution.',
    )
    in_weight = File(
        exists=True,
        argstr='--inweight=%s',
        desc='cost function weighting for input - weights data in vertices when calculating similarity '
        '(ASCII or GIFTI). Can be multivariate if dimension equals data dimension.',
    )
    reference_weight = File(
        exists=True,
        argstr='--refweight=%s',
        desc='cost function weighting for reference - weights data in vertices when calculating similarity '
        '(ASCII or GIFTI). Can be multivariate if dimension equals data dimension.',
    )
    output_format = traits.Enum(
        'GIFTI',
        'VTK',
        'ASCII',
        'ASCII_MAT',
        argstr='--format=%s',
        desc='format of output files',
    )
    config_file = File(
        exists=True,
        argstr='--conf=%s',
        desc='configuration file',
    )
    levels = traits.Int(
        argstr='--levels=%d',
        desc='number of resolution levels (default = number from --opt in config file)',
    )
    smooth_output_sigma = traits.Int(
        argstr='--smoothout=%d',
        desc='smooth transformed output with this sigma (default=0)',
    )
    verbose = traits.Bool(
        argstr='--verbose',
        desc='switch on diagnostic messages',
    )


class MSMOutputSpec(TraitedSpec):
    """Output specification for MSM interface."""

    warped_mesh = File(
        desc='warped input mesh (new vertex locations - captures warp field like _warp.nii.gz)',
    )
    downsampled_warped_mesh = File(
        desc='downsampled warped_mesh at final datamesh resolution',
    )
    warped_data = File(
        desc='input data passed through MSM warp and projected onto target surface',
    )


class MSM(CommandLine):
    """
    Multimodal Surface Matching (MSM) interface for cortical surface registration.

    MSM is a tool for registering cortical surfaces using discrete optimization.
    Developed and tested with FreeSurfer surfaces, but works with any cortical
    extraction method that can map surfaces to the sphere.

    Key advantages:
    - Alignment driven by univariate features (sulcal depth, curvature, myelin)
    - Multivariate data support (Task fMRI, Resting State Networks)
    - Multimodal registration (folding + myelin + fMRI combinations)
    - Fast alignment using discrete optimization (FastPD)
    - Flexible similarity metrics

    Examples
    --------
    >>> from oncoprep.interfaces import MSM
    >>> msm = MSM(
    ...     config_file='MSMSulcStrainFinalconf',
    ...     in_mesh='sub-01_hemi-L_sphere.surf.gii',
    ...     reference_mesh='tpl-fsaverage_hemi-L_den-164k_sphere.surf.gii',
    ...     in_data='sub-01_hemi-L_sulc.shape.gii',
    ...     reference_data='tpl-fsaverage_hemi-L_den-164k_sulc.shape.gii',
    ...     out_base='L.',
    ... )
    >>> 'msm' in msm.cmdline
    True

    Notes
    -----
    Output files generated by MSM:
    - sphere.reg.surf.gii - registered sphere with new mesh
    - sphere.LR.reg.surf.gii - downsampled registered sphere
    - transformed_and_reprojected.func.gii - data transformed and reprojected

    """

    input_spec = MSMInputSpec
    output_spec = MSMOutputSpec
    _cmd = 'msm'

    def _list_outputs(self):
        """Generate output filenames from base name."""
        from nipype.utils.filemanip import split_filename

        outputs = self._outputs().get()
        out_base = self.inputs.out_base or split_filename(self.inputs.in_mesh)[1]
        cwd = Path.cwd()
        outputs['warped_mesh'] = str(cwd / (out_base + 'sphere.reg.surf.gii'))
        outputs['downsampled_warped_mesh'] = str(cwd / (out_base + 'sphere.LR.reg.surf.gii'))
        outputs['warped_data'] = str(cwd / (out_base + 'transformed_and_reprojected.func.gii'))
        return outputs


__all__ = ['MSM']
