"""Supplementary S1: CLAIM checklist generation (2024 update).

Auto-generates a filled CLAIM checklist mapping items to manuscript sections,
based on the validation protocol and results.

Usage:
    python -m validation.claim_checklist --output ./tables/S1_CLAIM.tex
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import List, Tuple

# CLAIM 2024 checklist items mapped to OncoPrep manuscript sections.
# Reference: https://pubs.rsna.org/doi/10.1148/radiol.2020200029
# Each entry: (item_number, category, item_text, manuscript_section)

CLAIM_ITEMS: List[Tuple[str, str, str, str]] = [
    # Title / Abstract
    ("1", "Title", "Identification as a study of AI methodology", "Title"),
    ("2", "Abstract", "Structured summary of study design, methods, results, conclusions", "Abstract"),

    # Introduction
    ("3", "Introduction", "Scientific and clinical background", "Introduction"),
    ("4", "Introduction", "Study objectives and hypotheses", "Introduction, Protocol §Objectives"),

    # Methods — Study design
    ("5", "Methods", "Prospective or retrospective study design", "Methods §Datasets (retrospective)"),
    ("6", "Methods", "Study sites and dates of data collection", "Methods §Datasets (UCSF-PDGM, MU-Glioma Post)"),
    ("7", "Methods", "Eligibility criteria (inclusion/exclusion)", "Methods §Datasets, Figure 2"),
    ("8", "Methods", "Data pre-processing steps", "Methods §Pipeline (Figure 1)"),

    # Methods — Data
    ("9", "Methods", "Source of data (training, validation, test)", "Methods §Datasets, Protocol §Split"),
    ("10", "Methods", "Definition of ground truth reference standard", "Methods §Datasets (GT type column Table 1)"),
    ("11", "Methods", "Rationale for reference standard", "Methods §Datasets"),
    ("12", "Methods", "Handling of missing data", "Methods §Phase A (failure taxonomy)"),
    ("13", "Methods", "Data augmentation or synthesis", "Methods §Phase C (perturbations as augmentation proxy)"),

    # Methods — Model
    ("14", "Methods", "Model architecture and details", "Methods §Pipeline architecture"),
    ("15", "Methods", "Software libraries, frameworks, versions", "Methods §Reproducibility, Table 4"),
    ("16", "Methods", "Initialization and training procedure", "N/A — OncoPrep uses pre-trained models"),
    ("17", "Methods", "Features / inputs used (modalities, ROIs)", "Methods §Input contract (T1w, ce-T1w, T2w, FLAIR)"),

    # Methods — Evaluation
    ("18", "Methods", "Metrics of model performance", "Methods §Endpoints B1–B2, Protocol §SAP"),
    ("19", "Methods", "Statistical methods for comparing models", "Methods §SAP (paired bootstrap, McNemar)"),
    ("20", "Methods", "Robustness / sensitivity analyses", "Methods §Phase C"),
    ("21", "Methods", "Methods for explainability / interpretability", "Methods §QC reports (Figure 7)"),

    # Results
    ("22", "Results", "Training/validation/test data demographics", "Results §Table 1"),
    ("23", "Results", "Model performance against reference standard", "Results §Table 2, Figures 4–5"),
    ("24", "Results", "Performance across subgroups", "Results §Volume-bin sensitivity, Phase C"),
    ("25", "Results", "Estimates of diagnostic accuracy with CIs", "Results §Tables 2–3"),
    ("26", "Results", "Failure case analysis", "Results §Phase A taxonomy, Figure 3B, Supp S5"),

    # Discussion
    ("27", "Discussion", "Study limitations", "Discussion §Limitations"),
    ("28", "Discussion", "Implications for practice", "Discussion §Clinical implications"),
    ("29", "Discussion", "Registration and protocol availability", "Discussion §Protocol (preregistered)"),

    # Other
    ("30", "Other", "Data and code availability", "Data Availability / Code Availability"),
    ("31", "Other", "Funding and COI", "Declarations"),
]


def generate_claim_latex(output_path: Path) -> None:
    """Generate CLAIM checklist as a LaTeX longtable."""
    lines = [
        r"% Supplementary S1: CLAIM Checklist (2024 update)",
        r"% Auto-generated by validation/claim_checklist.py",
        r"\begin{longtable}{p{0.5cm}p{2cm}p{6cm}p{4cm}}",
        r"\caption{CLAIM checklist mapping to manuscript sections.} \\",
        r"\toprule",
        r"\textbf{\#} & \textbf{Section} & \textbf{CLAIM Item} & \textbf{Manuscript Location} \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"\textbf{\#} & \textbf{Section} & \textbf{CLAIM Item} & \textbf{Manuscript Location} \\",
        r"\midrule",
        r"\endhead",
    ]

    for num, category, item, location in CLAIM_ITEMS:
        item_escaped = item.replace("&", r"\&")
        location_escaped = location.replace("&", r"\&").replace("§", r"\S ")
        lines.append(f"{num} & {category} & {item_escaped} & {location_escaped} \\\\")

    lines.extend([
        r"\bottomrule",
        r"\end{longtable}",
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(lines))
    print(f"CLAIM checklist saved to: {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate CLAIM checklist (Supp S1)")
    parser.add_argument("--output", type=Path, default=Path("tables/S1_CLAIM.tex"))
    args = parser.parse_args()
    generate_claim_latex(args.output)


if __name__ == "__main__":
    main()
